---
dist: trusty
sudo: required
language: go

go_import_path: github.com/contiv/vpp

git:
  depth: 1

go:
  - 1.11.x

cache:
  directories:
    - $HOME/build-cache

env:
  - GO_BUILD_TAGS=mockvpp

before_install:
  - make get-linkcheck
  - make get-linters
  - make get-covtools

script:
  - make check-format
  - make lint
  - make lint-yaml
  - make lint-helm
  - make
  - make test-cover
  - make check-links || true

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
