# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/wadey/gocovmerge", "github.com/docker/docker/api", "github.com/docker/swarmkit", "github.com/opencontainers/runc", "golang.org/x/exp/inotify", "github.com/google/cadvisor", "k8s.io/apiserver/pkg/apis/apiserver", "github.com/ugorji/go/codec", "github.com/docker/distribution"]

[[constraint]]
  revision = "0456d22f67865977065886ed58778621b21b7ede"
  name = "git.fd.io/govpp.git"

[[constraint]]
  revision = "b5bfa59ec0adc420475f97f89b58045c721d761c"
  name = "github.com/wadey/gocovmerge"

[[constraint]]
  revision = "1c81e2a794c6e26a4c650142ae8893c47f619764"
  name = "github.com/opencontainers/runc"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "a35277792fddcf69f8cbbb8a9cb7727b23077409"

[[constraint]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/ligato/cn-infra"
  revision = "e5bff3cae460e0e45770b9840ddf863da8540d72"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.6.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "008b217844f8738cc47ef9ff108dc41dc37736cc"

[[constraint]]
  name = "github.com/google/cadvisor"
  revision = "cda62a43857256fbc95dd31e7c810888f00f8ec7"

[[constraint]]
  name = "github.com/docker/swarmkit"
  source = "https://github.com/dmcgowan/swarmkit.git"
  revision = "8bdecc57887ffc598b63d6433f58e0d2852112c3"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/ligato/vpp-agent"
  revision = "4db11634e69208566fd09839f17077f28fa19ce4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.2.1"

[[constraint]]
  name = "golang.org/x/exp"
  revision = "292a51b8d262487dab23a588950e8052d63d9113"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.8.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "82aa063804cf055e16e8911250f888bc216e8b61"

[[constraint]]
  name = "github.com/nerdtakula/supervisor"
  revision = "5bf894f54fd79a23fa965bf078b2a094a9d9e20b"

[[constraint]]
  name = "github.com/safchain/ethtool"
  revision = "7ff1ba29eca231991280817541cb3903f6be15d1"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  branch = "master"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "2bd8b58cf4275aeb086ade613de226773e29e853"

[prune]
  go-tests = true
  unused-packages = true
