---
# Create three linux CNFs - the second CNFs with 2 tap intefaces - for multi-node SFC
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf7
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf7
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeSelector:
    nodetype: master
---
# Linux CNF 3 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf8
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf8
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
