apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-agent-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 5000000000
    endpoints:
      - "10.20.0.2:32379"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }

---
