# Configuration for node in the cluster
apiVersion: nodeconfig.contiv.vpp/v1
kind: NodeConfig
metadata:
  name: k8s-master
spec:
  mainVPPInterface: 
    interfaceName: "GigabitEthernet0/8/0"
    ip: "192.168.16.1/24"

---

# Configuration for node in the cluster
apiVersion: nodeconfig.contiv.vpp/v1
kind: NodeConfig
metadata:
  name: k8s-worker1
spec:
  mainVPPInterface: 
    interfaceName: "TenGigabitEthernet4/0/0"
    ip: "192.168.16.1/24"
