apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # ldpreload-related labels
        ldpreload: "true"
        scopeglobal: "true"
    spec:
      # optional - deploy on preferred node
      nodeSelector:
        kubernetes.io/hostname: ubuntu
      containers:
      - image: networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf-server
        ports:
        - containerPort: 5201
        command: ["iperf3"]
        args: ["-V4d", "-s"]
        securityContext:
          privileged: true